pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo $M2_HOME'
                sh 'echo $MAVEN_HOME'
                sh 'echo Hi!!'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
